services:
  cv-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: amywoodehy/cv2doc
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    #    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
